document.querySelector('button[data-a-target="player-settings-button"]').click()
document.querySelector('button[data-a-target="player-settings-menu-item-quality"]').click()
document.querySelectorAll('div[data-a-target="player-settings-menu"] .tw-pd-05')[2].querySelector('input').click()
document.querySelector('button[data-a-target="player-theatre-mode-button"]').click()
// document.querySelector('[data-a-target="player-fullscreen-button"]').click()